# ──────────────────────────────────────────────────────────────────────────────
# Build & Deploy FastAPI container ➟ Google Artifact Registry ➟ Cloud Run
# Trigger: push to main
# Prerequisites (once per project):
#   1. Enable APIs: artifactregistry.googleapis.com, run.googleapis.com,
#      iamcredentials.googleapis.com
#   2. Create Workload Identity Pool + Provider pointing to
#      https://token.actions.githubusercontent.com
#   3. Create a service account, grant it:
#        • roles/artifactregistry.admin
#        • roles/run.developer
#      and bind it to the provider with roles/iam.workloadIdentityUser.
# Docs: https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation
# ──────────────────────────────────────────────────────────────────────────────

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: mamtha-mishra-17388               # ▼── GCP project ID
  GAR_NAME: my-repo                             # ▼── Artifact Registry repo
  REGION: us-central1                           # ▼── GCP region
  SERVICE: fastapi-shopping-data                # ▼── Cloud Run service name
  WORKLOAD_IDENTITY_PROVIDER: >-
    projects/478336148294/locations/global/workloadIdentityPools/github-demo/providers/github-wfi-demo
  SERVICE_ACCOUNT: github-cloudrun-deployer@mamtha-mishra-17388.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read        # checkout
      id-token: write       # OIDC token for Workload Identity Federation

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # ── Authenticate to Google Cloud via Workload Identity Federation ─────────
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    # ── Build & push container to Artifact Registry ───────────────────────────
    - name: Configure Artifact Registry Docker auth
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and push container
      run: |
        IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
        echo "Building image ${IMAGE}"
        docker build -t "${IMAGE}" .
        docker push "${IMAGE}"

    # ── Deploy to Cloud Run ───────────────────────────────────────────────────
    - id: deploy
      name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        region:  ${{ env.REGION }}
        image:   ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}

    # ── Output Cloud Run URL so you can click it in job logs ──────────────────
    - name: Show service URL
      run: echo "✅ Deployed URL ➜ ${{ steps.deploy.outputs.url }}"
