name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'mamtha-mishra-17388'                     # Your GCP Project ID
  GAR_NAME: 'my-repo'                                   # Artifact Registry repo name
  REGION: 'us-central1'                                 # GCP region
  SERVICE: 'fastapi-shopping-data'                      # Cloud Run service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/478336148294/locations/global/workloadIdentityPools/github-demo/providers/github-wfi-demo'
  SERVICE_ACCOUNT: 'github-wfi@mamtha-mishra-17388.iam.gserviceaccount.com'  # Your SA email

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needed for Workload Identity Federation OIDC token

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "Building image ${IMAGE}"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show Deployed Service URL
        run: |
          gcloud run services describe ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --format 'value(status.url)'
